# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        arch: [arm64]
        node-version: [14.x, 16.x]
        mongodb-version: ['4.2', '4.4']
        python-version:
          ['2.7', '3.7', '3.8', '3.9', '3.10', 'pypy-2.7', 'pypy-3.8']

    steps:
      - name: Install g++-aarch64-linux-gnu
        if: matrix.os == 'ubuntu-latest' && matrix.arch == 'arm64'
        run: sudo apt update && sudo apt install g++-aarch64-linux-gnu -y
      - name: Build V8 linux
        if: matrix.platform == 'ubuntu-latest'
        run: cd deps && ./build.py --no-clang --arch ${{ matrix.arch }}
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3.0.0
        with:
          always-auth: false
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Start MongoDB v${{ matrix.mongodb-version }}
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - run: npm ci
      - run: npm test
        env:
          CI: true
